import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import Hero from '@/components/Hero'
import Party from '@/components/Party'
import Story from '@/components/Story'
import Footer from '@/components/Footer'
import RSVP from '@/components/RSVP'
import Schedule from '@/components/Schedule'
import Registry from '@/components/Registry'
import Deets from '@/components/Deets'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Jerrod & Constancia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header active="home" />
      {/* <Banner /> */}
      <Hero />
      <main className='p-10'>
        <Deets />
        <Story />
        <Party />
        {/* venue Info */}
        {/* schedule */}
        <Schedule />
        {/* Registry */}
        <Registry />
        {/* RSVP */}
        <RSVP />

      </main>
      <Footer />
    </>
  )
}
